---
- name: Set up macOS CI runner
  hosts: macos
  remote_user: ec2-user

  tasks:
  - name: Install files in home directory
    ansible.builtin.copy:
      src: macos/{{ item }}
      dest: ~/{{ item }}
    loop:
      - .zshrc
      - .bashrc
      - .zshenv

  - name: Tap homebrew/cask-fonts repository, state present
    community.general.homebrew_tap:
      name:  homebrew/cask-fonts

  - name: Install Homebrew packages
    community.general.homebrew:
      name: "{{ item }}"
      state: present
    loop:
      - ruby
      - tmux
      - ninja
      - nvm
      - pyenv
      - cmake
      - node
      - ccache
      - pkg-config
      - glfw
      - bazelisk

  - name: Install font-noto-sans-cjk
    community.general.homebrew_cask:
      name: font-noto-sans-cjk
      state: present

  - name: Install gems
    community.general.gem:
      name: jazzy
      user_install: false
      executable: /opt/homebrew/opt/ruby/bin/gem
    loop:
      - jazzy
      - xcpretty
      - cocoapods

  # https://github.com/ffi/ffi/issues/864
  - name: Install ffi gem, required for jazzy to function
    community.general.gem:
      name: ffi
      user_install: false
      build_flags: --enable-libffi-alloc
      executable: /opt/homebrew/opt/ruby/bin/gem

  - name: Copy provisioning profile
    ansible.builtin.copy:
      src: secrets/MapLibre.mobileprovision
      dest: ~/MapLibre.mobileprovision
